events {}

http {
    access_log off;
    server_tokens off;

    server {
        listen 80;
        server_name camouflage.local;

        location / {
            default_type text/plain;
            return 200 "local camouflage endpoint\n";
        }
    }

    server {
        listen 443 ssl;
        server_name camouflage.local;
        ssl_certificate /run/xray/camouflage.crt;
        ssl_certificate_key /run/xray/camouflage.key;

        location / {
            default_type text/plain;
            return 200 "local camouflage endpoint\n";
        }
    }
}
